### ISSUE TITLE
Questions for ivan-developer-01

### ISSUE THREAD

**Issue by Yort6141** [ivan-developer-01/ivan-developer-01#3]
### Discussed in https://github.com/ivan-developer-01/ivan-developer-01/discussions/1

<div type='discussions-op-text'>

<sup>Originally posted by **ivan-developer-01** September 25, 2023</sup>
Ask questions for me here.

*I am leaving the right for me to not answer the questions when I don't want.*

I am open for ideas.</div>

**Comment by ivan-developer-01** [comment]
Welcome to GitHub!
